### ISSUE TITLE
How to get text with undelined format? 

### ISSUE THREAD

**Issue by root1991** [windyzboy/CustomEditor#4]
Hi!
I need to save text with underlined format. When I use getText(), it returns me just text without any tags, related to Underline Span. Any ideas?

**Comment by trietphm** [comment]
Hi root1991,
To save formated text, you must use `Html.toHtml()` or `getTextHTML()` to get HTML code and save it. And use `Html.fromHtml` to set text. Ex:
`myTextView.setText(Html.fromHtml("<b><i><u><font color="#FF0000">Hello world</font></u><i><b>"));`
